// <auto-generated />
using System;
using System.Collections.Generic;
using Kitchen.Infra.KitchenConnectionContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchen.Infra.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240506195407_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kitchen.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.GroupsOnInputs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId1")
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IngredientId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId1");

                    b.HasIndex("IngredientId1");

                    b.ToTable("GroupsOnInputs");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("GroupIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MeasurementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeasurementId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId1");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.GroupsOnInputs", b =>
                {
                    b.HasOne("Kitchen.Domain.Entities.Group", "Group")
                        .WithMany("GroupsOnInputs")
                        .HasForeignKey("GroupId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kitchen.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("GroupsOnInputs")
                        .HasForeignKey("IngredientId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("Kitchen.Domain.Entities.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupsOnInputs");
                });

            modelBuilder.Entity("Kitchen.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("GroupsOnInputs");
                });
#pragma warning restore 612, 618
        }
    }
}
